added msg.sh
Signed-off-by: kokkiemouse <kokkiemouse@fascode.net>

diff --git a/archiso/mkarchiso b/archiso/mkarchiso
--- a/archiso/mkarchiso
+++ b/archiso/mkarchiso
@@ -12,12 +12,14 @@ export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-"$(date +%s)"}"
 # mkarchiso defaults
 app_name="${0##*/}"
 pkg_list=()
+pkg_list_aur=()
 quiet="y"
 work_dir="work"
 out_dir="out"
 img_name="${app_name}.iso"
 gpg_key=""
 override_gpg_key=""
+script_path="$( cd -P "$( dirname "$(readlink -f "$0")" )" && pwd )"
 
 # profile defaults
 profile=""
@@ -43,26 +45,56 @@ declare -A file_permissions=()
 # Show an INFO message
 # $1: message string
 _msg_info() {
-    local _msg="${1}"
-    [[ "${quiet}" == "y" ]] || printf '[%s] INFO: %s\n' "${app_name}" "${_msg}"
+    #local _msg="${1}"
+    #[[ "${quiet}" == "y" ]] || printf '[%s] INFO: %s\n' "${app_name}" "${_msg}"
+
+    local _msg_opts="-a mkarchiso"
+    if [[ "${1}" = "-n" ]]; then
+        _msg_opts="${_msg_opts} -o -n"
+        shift 1
+    fi
+    [[ "${msgdebug}" = true ]] && _msg_opts="${_msg_opts} -x"
+    [[ "${nocolor}"  = true ]] && _msg_opts="${_msg_opts} -n"
+    "${script_path}/../scripts/msg.sh" ${_msg_opts} info "${1}"
 }
 
 # Show a WARNING message
 # $1: message string
 _msg_warning() {
-    local _msg="${1}"
-    printf '[%s] WARNING: %s\n' "${app_name}" "${_msg}" >&2
+    #local _msg="${1}"
+    #printf '[%s] WARNING: %s\n' "${app_name}" "${_msg}" >&2
+
+    local _msg_opts="-a mkarchiso"
+    if [[ "${1}" = "-n" ]]; then
+        _msg_opts="${_msg_opts} -o -n"
+        shift 1
+    fi
+    [[ "${msgdebug}" = true ]] && _msg_opts="${_msg_opts} -x"
+    [[ "${nocolor}"  = true ]] && _msg_opts="${_msg_opts} -n"
+    "${script_path}/../scripts/msg.sh" ${_msg_opts} warn "${1}"
 }
 
 # Show an ERROR message then exit with status
 # $1: message string
 # $2: exit code number (with 0 does not exit)
 _msg_error() {
-    local _msg="${1}"
-    local _error=${2}
-    printf '[%s] ERROR: %s\n' "${app_name}" "${_msg}" >&2
-    if (( _error > 0 )); then
-        exit "${_error}"
+    #local _msg="${1}"
+    #local _error=${2}
+    #printf '[%s] ERROR: %s\n' "${app_name}" "${_msg}" >&2
+    #if (( _error > 0 )); then
+    #    exit "${_error}"
+    #fi
+
+    local _msg_opts="-a mkarchiso"
+    if [[ "${1}" = "-n" ]]; then
+        _msg_opts="${_msg_opts} -o -n"
+        shift 1
+    fi
+    [[ "${msgdebug}" = true ]] && _msg_opts="${_msg_opts} -x"
+    [[ "${nocolor}"  = true ]] && _msg_opts="${_msg_opts} -n"
+    "${script_path}/../scripts/msg.sh" ${_msg_opts} error "${1}"
+    if [[ -n "${2:-}" ]]; then
+        exit ${2}
     fi
 }
 
@@ -133,6 +165,7 @@ _show_config() {
     _msg_info "          ISO application:   ${iso_application}"
     _msg_info "               Boot modes:   ${bootmodes[*]}"
     _msg_info "                 Packages:   ${pkg_list[*]}"
+    _msg_info "             AUR Packages:   ${pkg_list_aur[*]}"
 }
 
 # Cleanup airootfs
