Fix indentation of previus commit
Signed-off-by: Gerardo Exequiel Pozzi <vmlinuz386@yahoo.com.ar>

diff --git a/archiso/mkarchiso b/archiso/mkarchiso
--- a/archiso/mkarchiso
+++ b/archiso/mkarchiso
@@ -226,9 +226,9 @@ _imgcommon () {
     cp "${work_dir}/isomounts" "${work_dir}/iso/"
 
     if ! sed "s|archisolabel=[^ ]*|archisolabel=${LABEL}|" -i ${work_dir}/iso/boot/isolinux/isolinux.cfg; then
-	    echo "Error: ${work_dir}/iso/boot/isolinux/isolinux.cfg, doesn't exist, aborting."
-		exit 1
-	fi
+        echo "Error: ${work_dir}/iso/boot/isolinux/isolinux.cfg, doesn't exist, aborting."
+        exit 1
+    fi
 }
 
 command_iso () {
