[archiso] Refactor: Use losetup from util-linux
New losetup from util-linux 2.21 uses new /dev/loop-control from Linux 3.1.

Needs mkinitcpio-0.8.2+ (provides modules.devname, or workaround with earlymodules=loop)

Get advantages from it! Removing custom shell code.

Signed-off-by: Gerardo Exequiel Pozzi <vmlinuz386@yahoo.com.ar>

diff --git a/archiso/hooks/archiso_loop_mnt b/archiso/hooks/archiso_loop_mnt
--- a/archiso/hooks/archiso_loop_mnt
+++ b/archiso/hooks/archiso_loop_mnt
@@ -10,15 +10,13 @@ run_hook () {
 archiso_loop_mount_handler () {
     newroot="${1}"
 
+    local _dev_loop
+
     msg ":: Setup a loop device from ${img_loop} located at device ${img_dev}"
     _mnt_dev "${img_dev}" "/run/archiso/img_dev" "-r"
 
-    _dev_loop=$(losetup -f)
-    if ! losetup "${_dev_loop}" "/run/archiso/img_dev/${img_loop}"; then
-        echo "ERROR: Setting loopback device '${_dev_loop}'"
-        echo "   for file '/run/archiso/img_dev/${img_loop}'"
-        echo "   Falling back to interactive prompt"
-        echo "   You can try to fix the problem manually, log out when you are finished"
+    if ! _dev_loop=$(losetup --find --show "/run/archiso/img_dev/${img_loop}"); then
+        echo "ERROR: Setting loopback device for file '/run/archiso/img_dev/${img_loop}'"
         launch_interactive_shell
     fi
 
