Add an error message when mounting aufs fails, then exit 1
Closes FS#13381.

Waiting 30 seconds for device /dev/archiso ...
SUCCESS: Mounted archiso volume successfully.
squashfs: version 4.0 (2009/01/31) Phillip Lougher
aufs 2-standalone.tree-20090907
:: Mounting root (aufs) filesystem
aufs au_xino_do_write:371:mount[407]: I/O Error, write failed (4294967268)
aufs au_xino_set:1115:mount[407]: I/O Error, failed creating xino(-5).
mount: Invalid argument
ERROR: while mounting root (aufs) filesystem.
Kernel panic - not syncing: Attempted to kill init!

Signed-off-by: Gerardo Exequiel Pozzi <vmlinuz386@yahoo.com.ar>

diff --git a/archiso/hooks/archiso b/archiso/hooks/archiso
--- a/archiso/hooks/archiso
+++ b/archiso/hooks/archiso
@@ -103,6 +103,10 @@ run_hook ()
 
     msg ":: Mounting root (aufs) filesystem"
     /bin/mount -t aufs -o dirs=/tmpfs=rw none /real_root
+    if [ $? -ne 0 ]; then
+        echo "ERROR: while mounting root (aufs) filesystem."
+        exit 1
+    fi
 
     export LOOP_NUM="0"
     msg ":: Mounting images"
