[archiso] Add checksum= boot param
Signed-off-by: Gerardo Exequiel Pozzi <vmlinuz386@yahoo.com.ar>

diff --git a/archiso/hooks/archiso b/archiso/hooks/archiso
--- a/archiso/hooks/archiso
+++ b/archiso/hooks/archiso
@@ -77,6 +77,16 @@ _mnt_sfs() {
     fi
 }
 
+_verify_checksum() {
+    local _status
+    cd "/bootmnt/${archisobasedir}"
+    md5sum -c checksum.md5 > /checksum.log 2>&1
+    _status=$?
+    cd "${OLDPWD}"
+    return ${_status}
+}
+
+
 run_hook() {
     [[ -z "${arch}" ]] && arch="$(uname -m)"
     [[ -z "${cowspace_size}" ]] && cowspace_size="75%"
@@ -133,6 +143,22 @@ archiso_mount_handler() {
         echo "   Falling back to interactive prompt"
         echo "   You can try to fix the problem manually, log out when you are finished"
         launch_interactive_shell
+    fi
+
+    if [[ "${checksum}" == "y" ]]; then
+        if [[ -f "/bootmnt/${archisobasedir}/checksum.md5" ]]; then
+            msg -n ":: Self-test requested, please wait..."
+            if _verify_checksum; then
+                msg "done. Checksum is OK, continue booting."
+            else
+                echo "ERROR: one or more files are corrupted"
+                echo "see /checksum.log for details"
+                launch_interactive_shell
+            fi
+        else
+            echo "ERROR: checksum=y option specified but checksum.md5 not found"
+            launch_interactive_shell
+        fi
     fi
 
     if [[ "${copytoram}" == "y" ]]; then
