launch interactive shell if ipconfig fails
Signed-off-by: Christian Hesse <mail@eworm.de>

diff --git a/archiso/initcpio/hooks/archiso_pxe_common b/archiso/initcpio/hooks/archiso_pxe_common
--- a/archiso/initcpio/hooks/archiso_pxe_common
+++ b/archiso/initcpio/hooks/archiso_pxe_common
@@ -25,7 +25,12 @@ run_hook () {
         fi
 
         # setup network and save some values
-        ipconfig "ip=${ip}"
+        if ! ipconfig "ip=${ip}"; then
+                echo "ERROR; Failed to configure network"
+                echo "   Falling back to interactive prompt"
+                echo "   You can try to fix the problem manually, log out when you are finished"
+                launch_interactive_shell
+        fi
 
         . /tmp/net-*.conf
 
